export const ADD_QUESTION = "ADD_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_STUDENT_QUESTIONS = "GET_STUDENT_QUESTIONS";
export const GET_QUESTION = "GET_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
